#!/bin/bash

echo -e "It will only update your repos not update your system ::\n"

sudo pacman -Sy i3 rofi dmenu polybar picom network-manager-applet copyq sof-firmware python-pywal feh pavucontrol xorg-xrandr

echo -e "\n[[ PLEASE NOTE ]] :: while installing betterlockscreen you will be asked to replace i3lock with i3lock-color, choose i3lock-color"

sleep 2

if command -v paru &> /dev/null; then
   echo -e "\nparu is installed.\n"
   paru -S betterlockscreen arcolinux-logout

elif command -v yay &> /dev/null; then
   echo -e "yay is installed.\n"
   yay -S betterlockscreen arcolinux-logout

else
   echo -e "Neither paru nor yay is installed.\n"

	read -p "Install paru? [recomenned] or continue manually [y/n] :: " choice
	if [ "$choice" = 'y' ] || [ "$choice" = 'Y' ]; then
		git clone https://aur.archlinux.org/paru.git
		cd paru
		makepkg -si
		cd ../
		paru -S betterlockscreen arcolinux-logout
	else

		echo -e "\nInstalling AUR packages manually :: \n"
		declare -A myArray
		col=2
		row=2

		myArray[0,0]="https://aur.archlinux.org/arcolinux-logout.git"
		myArray[1,0]="https://aur.archlinux.org/betterlockscreen.git"
		myArray[0,1]="arcolinux-logout"
		myArray[1,1]="betterlockscreen"

		for ((i=0; i<row; i++)); do
			for ((j=0; j<col; j++)); do
				if [ $j -eq 1 ]; then
					continue
				fi
				
				git clone ${myArray[$i,$j]}
				cd ${myArray[$i,$((j+1))]}
				makepkg -si
				
				# sleep 3
			done
		done
	fi
fi

read -p "want to install warp terminal? [P.S. If you choose no here you must go into i3 config file and change the default terminal] (y/n)" choice1

if [ "$choice1" = 'y' ] || [ "$choice1" = 'Y' ]; then
	
	sudo pacman-key -r "linux-maintainers@warp.dev" --keyserver hkp://keys.openpgp.org:80 && \\nsudo pacman-key --lsign-key "linux-maintainers@warp.dev" && \\nmkdir -p /home/shyamendrahazra/.cache/warp-terminal && \\ncp /etc/pacman.conf /home/shyamendrahazra/.cache/warp-terminal && \\nsudo sh -c "echo '\n[warpdotdev]\nServer = https://releases.warp.dev/linux/pacman/\$repo/\$arch' >> /etc/pacman.conf" && \\nsudo pacman -Sy warp-terminal && warp_finish_update gCva7rd

fi

